AWSTemplateFormatVersion: '2010-09-09'
Description: Roles and policies creation for EMR 
Parameters:
  PermissionBoundary:
    Description: Permission boundary used for creation of roles 
    Type: String
    Default: arn:aws:iam::371666194988:policy/permissionboundary01
Resources:
  EMRClusterautoscaleRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DAL-EMR-AutoscalingRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - elasticmapreduce.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonElasticMapReduceforAutoScalingRole

      PermissionsBoundary:
        Ref: PermissionBoundary
      Path: "/"
Outputs:
  EMRClusterautoscaleRoleArn:
    Description: Emr  autoscale role 
    Value: !GetAtt EMRClusterautoscaleRole.Arn
    Export:
      Name: !Join [":",[!Ref "AWS::StackName","EMRClusterautoscaleRole::Arn"]]