---
AWSTemplateFormatVersion: '2010-09-09'
Description: Roles and policies creation for EMR 
Parameters:
  PermissionBoundary:
    Description: Permission boundary used for creation of roles 
    Type: String
    Default: arn:aws:iam::371666194988:policy/permissionboundary01

Resources:
  EMRClusterServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DAL-EMR-EMRClusterServiceRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - elasticmapreduce.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonElasticMapReduceRole
      PermissionsBoundary:
        Ref: PermissionBoundary
      Path: "/"
  EMRClusterinstanceProfileRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DAL-EMR-EMRClusterInstanceProfileRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonElasticMapReduceforEC2Role
      PermissionsBoundary:
        Ref: PermissionBoundary
      Path: "/"
  EMRClusterinstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:

      Path: "/"
      Roles:
      - Ref: EMRClusterinstanceProfileRole
Outputs:
  EMRClusterinstanceProfileRoleArn:
    Description: Emr role 
    Value: !GetAtt EMRClusterinstanceProfileRole.Arn
    Export:
      Name: !Join [":",[!Ref "AWS::StackName","EMRClusterinstanceProfileRole::Arn"]]

  EMRClusterServiceRoleArn:
    Description: Emr Service role 
    Value: !GetAtt EMRClusterServiceRole.Arn
    Export:
      Name: !Join [":",[!Ref "AWS::StackName","EMRClusterServiceRole::Arn"]]
  EMRClusterinstanceProfile:
    Description: Emr instance profile 
    Value: !GetAtt EMRClusterinstanceProfile.Arn
    Export:
      Name: !Join [":",[!Ref "AWS::StackName","EMRClusterinstanceProfile::Arn"]]
  
 


