AWSTemplateFormatVersion: '2010-09-09'
Description: role creation
Resources:
  EMRClusterinstancerole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DAL-EMR-EMRinstancerole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonElasticMapReduceforEC2Role
      Path: "/"